from voice import speak, takeCommand
import random

def get_jokes():
    jokes = [
        "¿Cuál es el último animal que subió al arca de Noé? —El del-fin.",
        "¿Cómo se dice pañuelo en japonés? —Saka-moko.",
        "¿Por qué los pájaros no usan Facebook? —Porque ya tienen Twitter.",
        "¿Qué hace una abeja en el gimnasio? —Zum-ba.",
        "¿Por qué no se puede discutir con un DJ? —Porque siempre está cambiando de tema.",
        "¿Cómo se llama el pez más divertido? —El pez payaso.",
        "¿Qué le dice una iguana a su hermana gemela? —Iguanita.",
        "¿Por qué el libro de matemáticas se deprimió? —Porque tenía demasiados problemas.",  
        "¿Qué hace un pez en el cine? —Ve la trama.",
        "¿Cuál es el colmo de Aladdín? —Tener mal genio.",
        "¿Qué hace una abeja en el ordenador? —Busca en Yahoo!",
        "¿Por qué los esqueletos no pelean entre ellos? —Porque no tienen agallas.",
        "¿Qué le dice una impresora a otra? —Esa hoja es tuya o es una copia.",
        "¿Cómo se dice nariz en inglés? —Nose.",
        "¿Por qué los pájaros no usan Instagram? —Porque ya tienen pajarogram.",
        "¿Qué hace una vaca con los ojos cerrados? —Leche concentrada.",
        "¿Qué le dice una iguana a su hermana gemela? —Somos iguanitas.",
        "¿Por qué las focas miran siempre hacia arriba? —¡Porque ahí están los focos!",
        "¿Cómo se llama un dinosaurio que no ha tomado café? —Dino-dormido.",
        "¿Qué hace una abeja en el gimnasio? —Zum-ba.",
        "¿Por qué los pájaros no juegan a las cartas? —Porque ya tienen plumaje.",
        "¿Qué hace un pez en el espacio? —Nada.",
        "¿Cómo se dice pañuelo en japonés? —Saka-moko.",
        "¿Cuál es el animal más antiguo? —La cebra, porque está en blanco y negro.",
        "¿Qué hace un perro con un taladro? —Taladrando.",
        "¿Cómo se dice pelo en inglés? —Hair.",
        "¿Por qué los pájaros no usan sombreros? —Porque ya tienen alas.",
        "¿Qué hace una abeja en el ordenador? —Busca en Yahoo!",
        "¿Por qué los esqueletos no pelean entre ellos? —Porque no tienen agallas.",
        "¿Qué le dice una impresora a otra? —Esa hoja es tuya o es una copia.",
        "¿Cómo se dice nariz en inglés? —Nose.",
        "¿Qué hace una abeja en el gimnasio? —Zum-ba.",
        "¿Por qué los pájaros no usan Facebook? —Porque ya tienen Twitter.",
        "¿Qué le dice una iguana a su hermana gemela? —Iguanita.",
        "¿Por qué el libro de matemáticas se deprimió? —Porque tenía demasiados problemas.",
        "¿Qué hace un pez en el cine? —Ve la trama.",
        "¿Cuál es el colmo de Aladdín? —Tener mal genio.",
        "¿Qué hace una abeja en el ordenador? —Busca en Yahoo!",
        "¿Por qué los esqueletos no pelean entre ellos? —Porque no tienen agallas.",
        "¿Qué le dice una impresora a otra? —Esa hoja es tuya o es una copia.",
        "¿Cómo se dice nariz en inglés? —Nose.",
        "¿Por qué los pájaros no usan Instagram? —Porque ya tienen pajarogram.",
        "¿Qué hace una vaca con los ojos cerrados? —Leche concentrada.",
        "¿Qué le dice una iguana a su hermana gemela? —Somos iguanitas.",
        "¿Por qué las focas miran siempre hacia arriba? —¡Porque ahí están los focos!",
        "¿Cómo se llama un dinosaurio que no ha tomado café? —Dino-dormido.",
        "¿Qué hace una abeja en el gimnasio? —Zum-ba.",
        "¿Por qué los pájaros no juegan a las cartas? —Porque ya tienen plumaje.",
        "¿Qué hace un pez en el espacio? —Nada.",
        "¿Cómo se dice pañuelo en japonés? —Saka-moko.",
    ]
    speak(random.choice(jokes))

get_jokes()